# Generated by Django 4.2.3 on 2023-08-01 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pumpsData", "0003_rename_mump_id_pumps_pump_id"),
        ("motorData", "0002_rename_pump_id_motor_pump"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupling",
            fields=[
                ("coupling_id", models.AutoField(primary_key=True, serialize=False)),
                ("motor_side_measure", models.CharField(max_length=100)),
                ("pump_side_sizer", models.CharField(max_length=100)),
                ("motor_key_measure", models.CharField(max_length=100)),
                ("pump_key_measure", models.CharField(max_length=100)),
                ("last_maintenance", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "motor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="motorData.motor",
                    ),
                ),
                (
                    "pump",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pumpsData.pumps",
                    ),
                ),
            ],
        ),
    ]
