# Generated by Django 4.2.3 on 2023-08-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("couplingData", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupling",
            name="last_maintenance",
        ),
        migrations.AlterField(
            model_name="coupling",
            name="motor_key_measure",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="coupling",
            name="motor_side_measure",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="coupling",
            name="pump_key_measure",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="coupling",
            name="pump_side_sizer",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
