# Generated by Django 4.2.3 on 2023-08-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("couplingData", "0002_remove_coupling_last_maintenance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupling",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="coupling",
            name="types",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
