# Generated by Django 4.2.3 on 2023-08-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("motorData", "0005_motor_anti_explosive_alter_motor_model"),
        ("couplingData", "0004_alter_coupling_motor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupling",
            name="motor",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="motorData.motor",
            ),
            preserve_default=False,
        ),
    ]
