# Generated by Django 4.2.3 on 2023-08-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("couplingData", "0005_alter_coupling_motor"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupling",
            name="image",
            field=models.ImageField(
                blank=True,
                default="img_coupling.png",
                upload_to="img_coupling/",
                verbose_name="Imagen de acolple",
            ),
        ),
    ]
