# Generated by Django 4.2.3 on 2023-08-01 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pumpsData", "0002_alter_pumps_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motor",
            fields=[
                ("motor_id", models.AutoField(primary_key=True, serialize=False)),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("hp", models.CharField(max_length=100)),
                ("rpm", models.CharField(max_length=100)),
                ("front_serial_number", models.CharField(max_length=100)),
                ("rear_serial_number", models.CharField(max_length=100)),
                ("last_maintenance", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="img_motor.png",
                        upload_to="img_motor/",
                        verbose_name="Imagen de motor",
                    ),
                ),
                (
                    "pump_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pumpsData.pumps",
                    ),
                ),
            ],
        ),
    ]
