# Generated by Django 4.2.3 on 2023-08-01 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("motorData", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="motor",
            old_name="pump_id",
            new_name="pump",
        ),
    ]
