# Generated by Django 4.2.3 on 2023-08-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motorData", "0002_rename_pump_id_motor_pump"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motor",
            name="front_serial_number",
        ),
        migrations.RemoveField(
            model_name="motor",
            name="last_maintenance",
        ),
        migrations.RemoveField(
            model_name="motor",
            name="rear_serial_number",
        ),
        migrations.AddField(
            model_name="motor",
            name="front_bearing",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="motor",
            name="rear_bearing",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="motor",
            name="brand",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="motor",
            name="hp",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="motor",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="motor",
            name="rpm",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
