# Generated by Django 4.2.4 on 2023-08-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorData', '0004_alter_motor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='anti_explosive',
            field=models.BooleanField(blank=True, default=False, verbose_name='Antiexplosivo'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Carcasa'),
        ),
    ]
