# Generated by Django 4.2.3 on 2023-08-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_profile_email_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="image_user.png",
                upload_to="users/",
                verbose_name="Imagen de perfil",
            ),
        ),
    ]
