# Generated by Django 4.2.3 on 2023-08-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pumps",
            fields=[
                ("mump_id", models.AutoField(primary_key=True, serialize=False)),
                ("types", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("tag", models.CharField(max_length=50, unique=True)),
                ("last_maintenance", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="pump_1.png",
                        upload_to="img_pumps/",
                        verbose_name="Imagende bomba",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MechanicalSeal",
            fields=[
                ("seal_id", models.AutoField(primary_key=True, serialize=False)),
                ("brand", models.CharField(max_length=100)),
                ("types", models.CharField(max_length=100)),
                ("extention", models.CharField(max_length=100)),
                ("last_maintenance", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "pumps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pumpsData.pumps",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bearing",
            fields=[
                ("bearing_id", models.AutoField(primary_key=True, serialize=False)),
                ("types", models.CharField(max_length=100)),
                ("amount", models.PositiveIntegerField()),
                ("front_serial_number", models.CharField(max_length=100)),
                ("rear_serial_number", models.CharField(max_length=100)),
                ("last_maintenance", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "pumps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pumpsData.pumps",
                    ),
                ),
            ],
        ),
    ]
