# Generated by Django 4.2.3 on 2023-08-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pumpsData", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pumps",
            name="image",
            field=models.ImageField(
                default="pump_1.png",
                upload_to="img_pumps/",
                verbose_name="Imagen de bomba",
            ),
        ),
    ]
