# Generated by Django 4.2.3 on 2023-08-01 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pumpsData", "0002_alter_pumps_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pumps",
            old_name="mump_id",
            new_name="pump_id",
        ),
    ]
