# Generated by Django 4.2.3 on 2023-08-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pumpsData", "0003_rename_mump_id_pumps_pump_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bearing",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bearing",
            name="front_serial_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="bearing",
            name="last_maintenance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bearing",
            name="rear_serial_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="bearing",
            name="types",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mechanicalseal",
            name="brand",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mechanicalseal",
            name="extention",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mechanicalseal",
            name="last_maintenance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mechanicalseal",
            name="types",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pumps",
            name="brand",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pumps",
            name="last_maintenance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pumps",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pumps",
            name="types",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
