# Generated by Django 4.2.3 on 2023-08-03 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pumpsData", "0004_alter_bearing_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bearing",
            old_name="front_serial_number",
            new_name="front_bearing",
        ),
        migrations.RenameField(
            model_name="bearing",
            old_name="rear_serial_number",
            new_name="rear_bearing",
        ),
        migrations.RemoveField(
            model_name="bearing",
            name="last_maintenance",
        ),
        migrations.RemoveField(
            model_name="mechanicalseal",
            name="last_maintenance",
        ),
        migrations.RemoveField(
            model_name="pumps",
            name="last_maintenance",
        ),
    ]
