# Generated by Django 4.2.3 on 2023-08-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pumpsData", "0005_rename_front_serial_number_bearing_front_bearing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pumps",
            name="image",
            field=models.ImageField(
                blank=True,
                default="pump_1.png",
                upload_to="img_pumps/",
                verbose_name="Imagen de bomba",
            ),
        ),
    ]
