# Generated by Django 4.2.3 on 2023-08-04 00:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pumpsData", "0007_rename_pumps_bearing_pump_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bearing",
            options={"ordering": ["bearing_id"], "verbose_name": "Rodamientos"},
        ),
        migrations.AlterModelOptions(
            name="mechanicalseal",
            options={
                "ordering": ["seal_id"],
                "verbose_name": "Sello",
                "verbose_name_plural": "Sellos",
            },
        ),
        migrations.AlterModelOptions(
            name="pumps",
            options={
                "ordering": ["tag"],
                "verbose_name": "bomba",
                "verbose_name_plural": "bombas",
            },
        ),
        migrations.AlterModelOptions(
            name="reten",
            options={
                "ordering": ["seal_id"],
                "verbose_name": "Reten",
                "verbose_name_plural": "Retenes",
            },
        ),
    ]
